### ISSUE TITLE
"this.addMatchers is not a function" error when running with protractor + jasmine 2

### ISSUE THREAD

**Issue by d3ming** [koola/pix-diff#48]
I'm just trying this out and followed the [example](https://github.com/koola/pix-diff/blob/master/docs/examples.md) to add pix-diff to the protractor conf.  I haven't even tried to actually use it in a spec yet, and just wanted to see if existing tests can run without a hitch.

However, I'm getting this error consistently:

```
[chrome #01-9]     Failed: this.addMatchers is not a function
[chrome #01-9]   Stack:
[chrome #01-9]     TypeError: this.addMatchers is not a function
[chrome #01-9]         at Object.<anonymous> (/Users/dongming/projects/placelocal/node_modules/pix-diff/framework/jasmine.js:7:10)
[chrome #01-9]         at /Users/dongming/projects/placelocal/node_modules/jasminewd2/index.js:94:23
[chrome #01-9]         at new ManagedPromise (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:1082:7)
[chrome #01-9]         at controlFlowExecute (/Users/dongming/projects/placelocal/node_modules/jasminewd2/index.js:80:18)
[chrome #01-9]         at TaskQueue.execute_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[chrome #01-9]         at TaskQueue.executeNext_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[chrome #01-9]         at asyncRun (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2775:27)
[chrome #01-9]         at /Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:639:7
[chrome #01-9]         at process._tickCallback (internal/process/next_tick.js:103:7)
[chrome #01-9]     From: Task: Run beforeEach in control flow
[chrome #01-9]         at Object.<anonymous> (/Users/dongming/projects/placelocal/node_modules/jasminewd2/index.js:79:14)
[chrome #01-9]         at /Users/dongming/projects/placelocal/node_modules/jasminewd2/index.js:16:5
[chrome #01-9]         at ManagedPromise.invokeCallback_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:1379:14)
[chrome #01-9]         at TaskQueue.execute_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[chrome #01-9]         at TaskQueue.executeNext_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[chrome #01-9]         at asyncRun (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2775:27)
[chrome #01-9]         at /Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:639:7
[chrome #01-9]         at process._tickCallback (internal/process/next_tick.js:103:7)
[chrome #01-9]     From asynchronous test:
[chrome #01-9]     Error
[chrome #01-9]         at Object.<anonymous> (/Users/dongming/projects/placelocal/node_modules/pix-diff/framework/jasmine.js:6:1)
[chrome #01-9]         at Module._compile (module.js:573:32)
[chrome #01-9]         at Object.Module._extensions..js (module.js:582:10)
[chrome #01-9]         at Module.load (/Users/dongming/projects/placelocal/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
[chrome #01-9]         at tryModuleLoad (module.js:449:12)
[chrome #01-9]         at Function.Module._load (module.js:441:3)
[chrome #01-9]         at Module.require (module.js:500:17)
[chrome #01-9]         at require (internal/module.js:20:19)
[chrome #01-9]         at PixDiff.browser.getProcessedConfig.then._ (/Users/dongming/projects/placelocal/node_modules/pix-diff/index.js:84:17)
[chrome #01-9]         at ManagedPromise.invokeCallback_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:1379:14)
[chrome #01-9]         at TaskQueue.execute_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[chrome #01-9]         at TaskQueue.executeNext_ (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[chrome #01-9]         at asyncRun (/Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:2775:27)
[chrome #01-9]         at /Users/dongming/projects/placelocal/node_modules/selenium-webdriver/lib/promise.js:639:7
[chrome #01-9]         at process._tickCallback (internal/process/next_tick.js:103:7)
```

Seems like it's using the `[framework/jasmine.js]`(https://github.com/koola/pix-diff/blob/master/framework/jasmine.js) instead of `jasmine2.js`?

I'm using jasmine 2.5.2 and protractor 4.0.9.  Any pointers would be appreciated!

**Comment by koola** [comment]
Hi @d3ming, could you try add ```framework: 'jasmine2'``` into your conf like [here](https://github.com/koola/pix-diff/blob/master/test/conf/protractor.shared.conf.js#L9) and try again.

**Comment by koola** [comment]
I've fixed this for when `framework` is omitted from the config in 0e8b0ebfea631d54c9d4ab70dcbd4f8b0b460889

**Comment by d3ming** [comment]
Thanks!

**Comment by mfulton26** [comment]
FYI: It may be a plugin or something that I am using but if I omit 'framework' from my config it gets recognized as ''jasmine'` instead of `'jasmine2'` because protractor itself is defaulting the value or some plugin is. I wonder if there is another way to determine which version of jasmine is being used...
